# Site settings
title: Sina Jahan's Logs
header-img: img/home-bg.jpg
url: "http://sinajahan.github.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
